images:
  - postgresci/golang:1.6
entrypoint:
  - /sbin/init
commands:
  - go version
  - sh test_setup.sh
  - echo ==== Tests ====
tests:
  - go test -cover -v github.com/postgres-ci/app-server/src/app
  - go test -cover -v github.com/postgres-ci/app-server/src/app/models/webhooks/common
  - go test -cover -v github.com/postgres-ci/app-server/src/app/models/webhooks/github
  - go test -cover -v github.com/postgres-ci/app-server/src/tools/limit
  - go test -cover -v github.com/postgres-ci/app-server/src/tools/render/pagination
