address   : ":8888"
loglevel  : "info" # info/warning/error
templates : "assets/templates/"

connect:
  host: "/var/run/postgresql"
  port: 5432
  username: "postgres_ci"
  password: "iAmAdiscoDancer"
  database: "postgres_ci"
